// <auto-generated />
namespace Code_First.Music_Collection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update));
        
        string IMigrationMetadata.Id
        {
            get { return "202107191743494_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
